name: dcg-gnn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pyyaml
  - click
  - tqdm
  - tensorboard
  - nbformat
  - nbconvert
  - pip:
      - hdf5storage
      - torch
      - torch-geometric
